// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXo75n2aId5SStMQx0CWWV7hmKE8SxRc',
    appId: '1:53872075328:web:53b4afb422fb27452e35a5',
    messagingSenderId: '53872075328',
    projectId: 'phoneauth-e9bee',
    authDomain: 'phoneauth-e9bee.firebaseapp.com',
    storageBucket: 'phoneauth-e9bee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6F_RwuHr63wdc8A49_ITxUhkzgOTSYOg',
    appId: '1:53872075328:android:af1095cd7347c6e42e35a5',
    messagingSenderId: '53872075328',
    projectId: 'phoneauth-e9bee',
    storageBucket: 'phoneauth-e9bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhNRx3jDuvqdrPLJz7jYfvSGlBajeV_0',
    appId: '1:53872075328:ios:503f1714712facce2e35a5',
    messagingSenderId: '53872075328',
    projectId: 'phoneauth-e9bee',
    storageBucket: 'phoneauth-e9bee.appspot.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhNRx3jDuvqdrPLJz7jYfvSGlBajeV_0',
    appId: '1:53872075328:ios:c7bd007e782cdd2a2e35a5',
    messagingSenderId: '53872075328',
    projectId: 'phoneauth-e9bee',
    storageBucket: 'phoneauth-e9bee.appspot.com',
    iosBundleId: 'com.example.phoneAuth.RunnerTests',
  );
}
